AllCops:
  TargetRubyVersion: 2.5

Lint/UselessAssignment:
  Enabled: false

Metrics/AbcSize:
  Max: 16

Metrics/LineLength:
  Max: 80

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MutableConstant:
  Enabled: false
